### ISSUE TITLE
support for .js files

### ISSUE THREAD

**Issue by kcoyner** [neoclide/coc-stylelint#1]
Supported file types are: 
css
wxss
scss
less
postcss
sugarss
vue

Would it support javascript (js) files?  I'm thinking of css-in-js ala styled-components.

It would be nice to have support for checking css via coc while in a JS file.

Thanks.

**Comment by chemzqm** [comment]
Let me know when stylelint have such kind of feature.

**Comment by antonk52** [comment]
I believe detecting errors should be possible via [styled components plugin](https://github.com/Microsoft/typescript-styled-plugin#linting). Not sure about the fixing them though.

**Comment by utrumo** [comment]
> Let me know when stylelint have such kind of feature.

 it's already work.
Please add stylelint.filetypes extension array parameter to coc config.
I need js extension support too.

https://43081j.com/2019/03/using-stylelint-with-lit
https://github.com/styled-components/stylelint-processor-styled-components

stylelintrc.js:
```
module.exports = {
  extends: [
    'stylelint-config-recommended',
    'stylelint-config-styled-components',
  ],
  plugins: [
    'stylelint-order',
  ],
  processors: [
    [
      'stylelint-processor-styled-components',
      {
        moduleName: 'lit-element',
        importName: 'css',
        strict: true,
        ignoreFiles: [
          '**/*.css',
        ],
      },
    ],
  ],
};
```
