### ISSUE TITLE
Errors on save

### ISSUE THREAD

**Issue by rtucek** [neoclide/coc-stylelint#17]
I get the following error when saving a file where coc-stylelint is in used:

```
[coc.nvim] TypeError: Cannot read property 'length' of undefined     at find_cursor_edit_diff (/home/rtucek/.vim/bundle/coc-stylelint/lib/server.js:8184:27)     at diff_main (/home/rtucek/.vim/bundle/coc-stylelint/lib/server.js:7552:20)
  at Object.diff [as default] (/home/rtucek/.vim/bundle/coc-stylelint/lib/server.js:8264:10)     at Object.getChange (/home/rtucek/.vim/bundle/coc-stylelint/lib/server.js:7459:37)     at Object.<anonymous> (/home/rtucek/.vim/bundle/coc-sty
"dev/App.vue" 184L, 4025C written
Press ENTER or type command to continue
```

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by rtucek** [comment]
Hi @chemzqm - thank you for looking into it!

I've tried out a few things and probably found a way to reproduce:
It happens if the plugin is installed via vim-plug - i.e. by using
```vim
Plug 'neoclide/coc-stylelint', {'do': 'yarn install --frozen-lockfile'}
```

Previously, I used to install plugins via
```vim
let g:coc_global_extensions = [
     \ 'coc-stylelint',
\ ]
```

I've a bunch of other coc-plugins migrated to vim-plug installation procedure too, but none of them seem to have issues being installed this way.

Also, vim-plug seems to detect installation errors properly if the hook-script from the `do` section exits with an error code. This was the main reason for my yesterday's mini PR #16
You can reproduce it by trying to install a revision prior to my fix:
```vim
Plug 'neoclide/coc-stylelint', {'do': 'yarn install --frozen-lockfile', 'commit': '7b678c4c1ae9d2b7091fa91d8a4bf91ab2271125'}
```

**Comment by chemzqm** [comment]
Need verbose output from language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by leanbalma** [comment]
I also started getting this in projects where I'm not using stylelint.
This is the output of the LS:

```
[Trace - 1:23:26 PM] Sending request 'textDocument/willSaveWaitUntil - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///path/to/file.js",
        "version": 1
    },
    "reason": 1
}


[Trace - 1:23:26 PM] Received request 'workspace/workspaceFolders - (4)'.
[Trace - 1:23:26 PM] Sending response 'workspace/workspaceFolders - (4)'. Processing request took 0ms
Result: [
    {
        "uri": "file:///path/to/folder",
        "name": "shell"
    }
]


[Trace - 1:23:26 PM] Received request 'window/showMessageRequest - (5)'.
Params: {
    "type": 1,
    "message": "TypeError: Cannot read property 'length' of undefined     at find_cursor_edit_diff (/Users/leandrobalmaceda/.config/nvim/plugged/coc-stylelint/lib/server.js:8183:27)     at diff_main (/Users/leandrobalmaceda/.config/nvim/plugged/coc-stylelint/lib/server.js:7551:20)     at Object.diff [as default] (/Users/leandrobalmaceda/.config/nvim/plugged/coc-stylelint/lib/server.js:8263:10)     at Object.getChange (/Users/leandrobalmaceda/.config/nvim/plugged/coc-stylelint/lib/server.js:7458:37)     at Object.<anonymous> (/Users/leandrobalmaceda/.config/nvim/plugged/coc-stylelint/lib/server.js:6530:35)     at Generator.next (<anonymous>)     at fulfilled (/Users/leandrobalmaceda/.config/nvim/plugged/coc-stylelint/lib/server.js:6435:58)",
    "actions": []
}


[Trace - 1:23:26 PM] Sending response 'window/showMessageRequest - (5)'. Processing request took 0ms
No result returned.


[Trace - 1:23:26 PM] Received response 'textDocument/willSaveWaitUntil - (2)' in 46ms.
Result: []


[Trace - 1:23:26 PM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///path/to/file.js",
        "version": 1
    }
}

```

**Comment by rtucek** [comment]
@leanbalma thank you for sharing your LS logs.

I'm not sure what I'm doing wrong, but I can't get the logs.
As far as I understand, based on the stylelint's package.json, a `trace.server` option is not supported, however `stylelint.execArgv` option is. So here's what I added to my .vimrc:

```vim
call coc#config('languageserver', {
	\ 'stylelint': {
		\ 'stylelint.execArgv': ['--nolazy', '--inspect-brk=6045'],
	\ },
\ })
```

But this leads to the following error:
```
[coc.nvim] Wrong configuration of LS "stylelint", filetypes not found
```

What am I doing wrong?

**Comment by leanbalma** [comment]
@rtucek I added `"stylelint.trace.server": "verbose"` anyway. It looks like it's not supported, but I guess it is?
Then ran `:CocCommand workspace.showOutput` and chose `stylelint`.

**Comment by rtucek** [comment]
@leanbalma thank you for you hint.
Unfortunately, it doesn't work for me and I still get `[coc.nvim] Wrong configuration of LS "stylelint", filetypes not found` error :/
Further, I can't see the `stylelint` option with `:CocCommand workspace.showOutput`

This is what I've added to my .vimrc.
```
call coc#config('languageserver', {
	\ 'stylelint': {
		\ 'stylelint.trace.server': 'verbose',
	\ },
\ })
```

@chemzqm could it be the case that there's something different if the plugins are installed via vim-plug and/or the config is stored in .vimrc rather than in a coc-settings.json file?

**Comment by chemzqm** [comment]
> could it be the case that there's something different if the plugins are installed via vim-plug and/or the config is stored in .vimrc rather than in a coc-settings.json file?

No, your configuration is wrong, configuration from coc extension doesn't belongs to `languageserver `

**Comment by rtucek** [comment]
Thx, for your help @chemzqm and @leanbalma. Finally, I got the config right. Not sure why I've failed understanding the config in first place... it's as simple as `call coc#config('stylelint.trace.server', 'verbose')` :see_no_evil:

I've attached my [coc-stylelint.log](https://github.com/neoclide/coc-stylelint/files/5308410/coc-stylelint.log). Seems to be exactly the same as @leanbalma encounters.
