### ISSUE TITLE
js support

### ISSUE THREAD

**Issue by utrumo** [neoclide/coc-stylelint#2]
What's news about .js files support?
Now it's perfect work with [stylelint-processor-styled-components extension](https://github.com/styled-components/stylelint-processor-styled-components) and vscode with [vscode-stylelint plugin](https://github.com/shinnn/vscode-stylelint).
Please look at this [post with working stylelint config](https://github.com/neoclide/coc-stylelint/issues/1#issuecomment-521372650)

Can you add support for .js extension?

**Comment by chemzqm** [comment]
Fixed
