### ISSUE TITLE
Add option to autofix

### ISSUE THREAD

**Issue by Axxxx0n** [neoclide/coc-stylelint#6]

**Comment by ubmit** [comment]
Why this issue was closed @chemzqm? Is it already possible to auto fix on save using coc-stylelint? I was trying to make it work but wasn't successful

**Comment by chemzqm** [comment]
No description

**Comment by Axxxx0n** [comment]
@guilhermedeandrade you can use [https://github.com/bmatcuk/coc-stylelintplus/tree/master](url) for autofixing

**Comment by ubmit** [comment]
> @guilhermedeandrade you can use [https://github.com/bmatcuk/coc-stylelintplus/tree/master](url) for autofixing

Thanks!

**Comment by kentarohorie** [comment]
I use coc-stylelintplus instead of coc-stylelint,  too.
https://github.com/bmatcuk/coc-stylelintplus
